name: My-tes-workflow
on: 
  pull_request:
      types:
        - opened
        - edited
      branches:
        - master
  push:
    branches:
      - master
    branches-ignore:
      - feature/*
    paths:
      - .github/workflows/*
  workflow_dispatch:

jobs:
  my-test-new-job:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
      - name: Install packages
        run: npm ci
      - name: Signal Completion
        run: |
          echo "This workflow completed"
          echo "Bye Bye"
